### PR TITLE
feat: support resolve_table for polars dataframe and arrow table

### PR DESCRIPTION
**Pull request by eitsupi**
```r
> df <- polars::as_polars_df(mtcars)
> glaredb_sql("select * from df") |> polars::as_polars_df()
shape: (32, 11)
┌──────┬─────┬───────┬───────┬───┬─────┬─────┬──────┬──────┐
│ mpg  ┆ cyl ┆ disp  ┆ hp    ┆ … ┆ vs  ┆ am  ┆ gear ┆ carb │
│ ---  ┆ --- ┆ ---   ┆ ---   ┆   ┆ --- ┆ --- ┆ ---  ┆ ---  │
│ f64  ┆ f64 ┆ f64   ┆ f64   ┆   ┆ f64 ┆ f64 ┆ f64  ┆ f64  │
╞══════╪═════╪═══════╪═══════╪═══╪═════╪═════╪══════╪══════╡
│ 21.0 ┆ 6.0 ┆ 160.0 ┆ 110.0 ┆ … ┆ 0.0 ┆ 1.0 ┆ 4.0  ┆ 4.0  │
│ 21.0 ┆ 6.0 ┆ 160.0 ┆ 110.0 ┆ … ┆ 0.0 ┆ 1.0 ┆ 4.0  ┆ 4.0  │
│ 22.8 ┆ 4.0 ┆ 108.0 ┆ 93.0  ┆ … ┆ 1.0 ┆ 1.0 ┆ 4.0  ┆ 1.0  │
│ 21.4 ┆ 6.0 ┆ 258.0 ┆ 110.0 ┆ … ┆ 1.0 ┆ 0.0 ┆ 3.0  ┆ 1.0  │
│ 18.7 ┆ 8.0 ┆ 360.0 ┆ 175.0 ┆ … ┆ 0.0 ┆ 0.0 ┆ 3.0  ┆ 2.0  │
│ …    ┆ …   ┆ …     ┆ …     ┆ … ┆ …   ┆ …   ┆ …    ┆ …    │
│ 30.4 ┆ 4.0 ┆ 95.1  ┆ 113.0 ┆ … ┆ 1.0 ┆ 1.0 ┆ 5.0  ┆ 2.0  │
│ 15.8 ┆ 8.0 ┆ 351.0 ┆ 264.0 ┆ … ┆ 0.0 ┆ 1.0 ┆ 5.0  ┆ 4.0  │
│ 19.7 ┆ 6.0 ┆ 145.0 ┆ 175.0 ┆ … ┆ 0.0 ┆ 1.0 ┆ 5.0  ┆ 6.0  │
│ 15.0 ┆ 8.0 ┆ 301.0 ┆ 335.0 ┆ … ┆ 0.0 ┆ 1.0 ┆ 5.0  ┆ 8.0  │
│ 21.4 ┆ 4.0 ┆ 121.0 ┆ 109.0 ┆ … ┆ 1.0 ┆ 1.0 ┆ 4.0  ┆ 2.0  │
└──────┴─────┴───────┴───────┴───┴─────┴─────┴──────┴──────┘
```

### CODE REVIEW

**Comment by yutannihilation** [comment]
Thanks for sharing, but it's not my preference to call R code on Rust's side. This is my approach:

https://github.com/yutannihilation/datafusionr/blob/4e2a7ea38da26317844ec2470a8e54cead38c73e/src/rust/src/lib.rs#L31-L39
https://github.com/yutannihilation/datafusionr/blob/4e2a7ea38da26317844ec2470a8e54cead38c73e/R/to_arrow_c_stream_interface.R

**Comment by eitsupi** [comment]
> This is my approach:
> 
> [yutannihilation/datafusionr@`4e2a7ea`/src/rust/src/lib.rs#L31-L39](https://github.com/yutannihilation/datafusionr/blob/4e2a7ea38da26317844ec2470a8e54cead38c73e/src/rust/src/lib.rs#L31-L39) [yutannihilation/datafusionr@`4e2a7ea`/R/to_arrow_c_stream_interface.R](https://github.com/yutannihilation/datafusionr/blob/4e2a7ea38da26317844ec2470a8e54cead38c73e/R/to_arrow_c_stream_interface.R)

Of course I read it in advance (very simply!).

My concern was that if we had to have my own classes wrap Array Stream when implementing the C Stream interface in all Arrow-based packages, we would have to create classes with non-conflicting class names just for import purposes and write functions on the R side.
(Of course that may be the right way to go, and I think I did that with the r-polars package because it is convenient to be able to add conversions from outside the package with S3 method. I was just wondering if it is necessary to create a new class and write an R file just for the conversion from nanoarrow_array_stream here.)

I think the export side would be fine as long as it supports `as_nanoarrow_array_stream.Foo()`.......
https://github.com/eitsupi/r-glaredb/blob/c5cfa08095e288ccf1dbff9f9057ee425fdc831c/R/execution.R#L2-L15

**Comment by yutannihilation** [comment]
> non-conflicting class names just for import purpose

It's not really necessary. I created a class in order to drop dependency on nanoarrow. If you have a function to allocate, you can get it as `Sexp` argument and cast to the FFI class directly.

Please note that, importing an external data struct is out of the primary scope of savvy. Savvy should provide whatever hacky way to archive this, but I'm not yet sure if this can be properly supported.

**Comment by eitsupi** [comment]
> If you have a function to allocate, you can get it as `Sexp` argument and cast to the FFI class directly.

I see, thanks.

**Pull request merged**
